# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6d77e9474020674353cb1a0f9fdb765c9a3295546b6b47cd180c8c336b073b76ae1a9c0d2d41d953b9ff65005872b755e489178873ea25d5cac073dc4a9658

test:
  secret_key_base: 87c2e9b5cf28249f12e4c17644180e597ea2fe441c3df9dd9205a27092f8cc64ed15ecc9857aa412f9f3dba2460582196273f49f200501771562532e689a0c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
